"""add api_key_prefix to tenants

Revision ID: 13d5a131bda4
Revises: 90f37fc7e262
Create Date: 2026-09-27 00:31:44.055967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d5a131bda4'
down_revision: Union[str, Sequence[str], None] = '90f37fc7e262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('api_key_prefix', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_tenants_api_key_prefix'), 'tenants', ['api_key_prefix'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_api_key_prefix'), table_name='tenants')
    op.drop_column('tenants', 'api_key_prefix')
    # ### end Alembic commands ###
