"""user: unique external_id

Revision ID: c8bb01fceabf
Revises: 13d5a131bda4
Create Date: 2026-09-28 23:17:32.101981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8bb01fceabf'
down_revision: Union[str, Sequence[str], None] = '13d5a131bda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_users_tenant_external_active'), table_name='users', postgresql_where='(is_active = true)')
    op.create_unique_constraint('uq_users_tenant_external', 'users', ['tenant_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_tenant_external', 'users', type_='unique')
    op.create_index(op.f('uq_users_tenant_external_active'), 'users', ['tenant_id', 'external_id'], unique=True, postgresql_where='(is_active = true)')
    # ### end Alembic commands ###
