"""add payload to notifications, title nullable

Revision ID: e3ec3bd4c289
Revises: c8bb01fceabf
Create Date: 2026-10-01 21:17:11.284531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3ec3bd4c289'
down_revision: Union[str, Sequence[str], None] = 'c8bb01fceabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('notifications', 'payload')
    # ### end Alembic commands ###
